import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'EasyShop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* nav kao komponentu*/}
        <nav className="bg-yellow-500 p-4">
          <ul className="flex justify-around">
            <li>
            <Link href="/">Home</Link>
            </li>
            <li>
              <Link href ="/about" >About us</Link>
           </li>
           <li>
              <Link href="/blog">Blog </Link>
           </li>
           <li>
            <Link href="/login">Login </Link>
           </li>
           <li>
           <Link href="/shopping-cart">Cart</Link>
           </li>
           <li>
           <Link href="/add-new">Add a product</Link>
           </li>
           <li>
           <Link href="/contact">Contact us</Link>
           </li>
           <li>
           <Link href="/blog">Blog</Link>
           </li>
          </ul>
        </nav>
        {children}
        </body>
    </html>
  )
}
